use_frameworks!

platform :ios, '9.0'

target 'ObjcUI_Example' do
  pod 'OCUI', :path => '../'
  pod 'ReactiveCocoa', '~> 10.1'
  pod 'ReactiveObjC','~> 3.1.1'
  pod 'YYModel'

  target 'ObjcUI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
