use_frameworks!

platform :ios, '9.0'

target 'ObjcUI_Example' do
  pod 'ObjcUI', :path => '../'

  target 'ObjcUI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
